### ISSUE TITLE
Obsolete?

### ISSUE THREAD

**Issue by hcderaad** [yast/yast-ca-management#22]
This module is heavily used by several of my clients, what has caused the discontinuation of this module? Does SUSE recommend an alternative? Perhaps DogTag?

**Comment by jreidinger** [comment]
@hcderaad I think main reason is lack of resources to maintain this module ( not sure if it is due to low usage of module or low interest in it, so priority was low for module and then discontinued ).

**Comment by hcderaad** [comment]
@jreidinger Ok, thanks for respondig. Would SUSE be willing to recommend or adopt an alternative for this module?

**Comment by divkoro** [comment]
Other YAST modules want to include CA's! And 15.1 docs still mention YAST-CA.
What is official SUSE recomendation for the alternative way of  setting up certificates?

**Comment by jreidinger** [comment]
@divkoro @hcderaad sadly currently I have no recommendation. The module was not maintained by YaST team, but other part of SUSE as we do not have enough CA knowledge and looks like priority shift.
Maybe @mcalmer has some recommendation here what can be used instead?

Regarding doc it needs to be update, to no longer mention this module.

**Comment by mcalmer** [comment]
AFAIK there is nothing you can use with YaST directly. If you need SSL Certificates the best thing you can currently do is, to have some fields to import an external generated certificate and just try you put it at the correct places.

You would need to ask for:

- the Server Certificate
- the private key
- the CA (Chain) - can be more than 1 certificate, but if the format is PEM, you can provide multiple in 1 file.

Now it depends on the service you configure where to put them and how to configure the service to use the correct certificates.

**Comment by ancorgs** [comment]
Closing the issue since no more activity is expected after the question has been answered (as much as we can answer it).
